# Docker Compose spec for running Home Assistant
# by @jareddantis, 2023
#
# Base path: /etc/docker/compose/homeassistant
# Required paths:
#   - config/
#     > create empty dir and copy configuration.yaml inside

version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    privileged: true
    volumes:
      - /etc/docker/compose/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      TZ: 'Asia/Manila'
