# Docker Compose spec for running Home Assistant
# by @jareddantis, 2023
#
# Base path: /etc/docker/compose/homeassistant
# Required paths:
#   - config/
#     > just create empty directories
#
# Notes:
#   1. Add the following to your configuration.yaml for HACS support:
#        # HACS
#        my:
#   2. Add the following to your configuration.yaml for reverse proxy support:
#        # Reverse proxy
#        http:
#          use_x_forwarded_for: true
#          trusted_proxies:
#            - 172.16.0.0/24     # Change to your local subnet or reverse proxy IP
#            - ::1               # For Argo Tunnel

version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    privileged: true
    volumes:
      - /etc/docker/compose/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      TZ: 'Asia/Manila'
