# Docker Compose spec for running Transmission
# by @jareddantis, 2023
#
# Base path: /etc/docker/compose/transmission
# Required paths:
#   - config/, watch/, filebrowser/
#     > just create empty directories
#   - downloads/
#     > either create empty directory, or change mount to desired downloads folder
#   - flood-for-transmission/
#     > download and unzip https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.zip
#
# Notes:
#   1. Add targets in config/Targets after first run

version: '3.8'
services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - TRANSMISSION_WEB_HOME=/ui/flood
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /etc/docker/compose/transmission/config:/config
      - /etc/docker/compose/transmission/downloads:/downloads
      - /etc/docker/compose/transmission/watch:/watch
      - /etc/docker/compose/transmission/flood-for-transmission:/ui/flood
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: transmission-filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
    volumes:
      - /etc/docker/compose/transmission/watch:/srv
      - /etc/docker/compose/transmission/filebrowser/filebrowser.db:/database/filebrowser.db
      - /etc/docker/compose/transmission/filebrowser/settings.json:/config/settings.json
    ports:
      - 9092:80
    restart: unless-stopped
