# Docker Compose spec for running Wireguard
# by @jareddantis, 2024
#
# Base path: /etc/docker/compose/wireguard
#
# Notes:
#   1. Tested with Mullvad.
#   2. Tunnel other containers through Wireguard by adding the following
#      to their Docker Compose specs:
#
#          network_mode: 'container:gluetun'
#
#   3. Change WIREGUARD_PRIVATE_KEY, WIREGUARD_ADDRESSES, and SERVER_HOSTNAMES
#      to your own values. Generate a .conf file through your VPN's website and
#      use the values from PrivateKey and Address. You can use multiple
#      servers by separating them with commas, or leave it blank to let
#      gluetun choose the best server for you.
#
#      Gluetun's current server list can be found here:
#
#          https://raw.githubusercontent.com/qdm12/gluetun/master/internal/storage/servers.json
#
#   4. To enable IPv6, uncomment the sysctl lines. Be aware that this might
#      cause gluetun to connect to your VPN over IPv6, which will fail if your
#      Docker host isn't native IPv6.

version: '3'

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9091:9091/tcp       # Transmission WebUI - comment this out if you're not using Transmission
      - 51413:51413         # Transmission inbound port - comment this out if you're not using Transmission
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - TZ=<changeme>
      - WIREGUARD_PRIVATE_KEY=[REDACTED]
      - WIREGUARD_ADDRESSES=[REDACTED]
      - SERVER_HOSTNAMES=<changeme>
    restart: unless-stopped
    # sysctls:
    #   - net.ipv6.conf.all.disable_ipv6=0
