# Docker Compose spec for running AdGuard Home with Unbound
# by @jareddantis, 2023-2024
#
# Base path: /etc/docker/compose/adguard
# Required paths:
#   - work/, conf/
#     > just create empty directories
#
# Notes:
#   1. This depends on the network specified in unbound.yml.
#   2. The sync container is configured for syncing with other AGH instances.
#      Feel free to remove the service if this does not apply to you.

version: '3'

services:
  agh:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped
    volumes:
      - '/etc/docker/compose/adguard-unbound/work:/opt/adguardhome/work'
      - '/etc/docker/compose/adguard-unbound/conf:/opt/adguardhome/conf'
      - '/etc/localtime:/etc/localtime:ro'
    ports:
      - 53:53/tcp         # Plain DNS
      - 53:53/udp         # Plain DNS
      - 80:80/tcp         # Admin
      - 443:443/tcp       # Admin, DNS-over-HTTPS
      - 443:443/udp       # Admin, DNS-over-HTTPS
      - 3000:3000/tcp     # Admin
      # - 853:853/tcp       # DNS-over-TLS
      # - 784:784/udp       # DNS-over-QUIC
      # - 853:853/udp       # DNS-over-QUIC
      # - 8853:8853/udp     # DNS-over-QUIC
      # - 5443:5443/tcp     # DNSCrypt
      # - 5443:5443/udp     # DNSCrypt
    networks:
      default:
        ipv4_address: 192.168.2.3

  sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    restart: unless-stopped
    command: run
    environment:
      LOG_LEVEL: "info"
      ORIGIN_URL: "http://192.168.196.1"
      ORIGIN_USERNAME: "[REDACTED]"
      ORIGIN_PASSWORD: "[REDACTED]"
      REPLICA1_URL: "http://192.168.196.2"
      REPLICA1_USERNAME: "[REDACTED]"
      REPLICA1_PASSWORD: "[REDACTED]"
      REPLICA2_URL: "http://192.168.196.3"
      REPLICA2_USERNAME: "[REDACTED]"
      REPLICA2_PASSWORD: "[REDACTED]"
      CRON: "30 5 * * *" # run at 5:30 AM
      RUNONSTART: true

      # Configure the sync API server, disabled if api port is 0
      API_PORT: 8080

      # Configure sync features; by default all features are enabled.
      # FEATURES_GENERALSETTINGS: true
      # FEATURES_QUERYLOGCONFIG: true
      # FEATURES_STATSCONFIG: true
      FEATURES_CLIENTSETTINGS: false
      # FEATURES_SERVICES: true
      # FEATURES_FILTERS: true
      FEATURES_DHCP_SERVERCONFIG: false
      FEATURES_DHCP_STATICLEASES: false
      FEATURES_DNS_SERVERCONFIG: false
      FEATURES_DNS_ACCESSLISTS: false
      # FEATURES_DNS_REWRITES: true
    networks:
      default:
        ipv4_address: 192.168.2.4
    ports:
      - 3001:8080
    volumes:
      - '/etc/localtime:/etc/localtime:ro'

networks:
  default:
    name: unbound
    external: true
