# Docker Compose spec for running Pi-hole with Unbound
# by @jareddantis, 2023-2024
#
# Base path: /etc/docker/compose/pihole
# Required paths:
#   - pihole/, dnsmasq.d/
#     > just create empty directories
#
# Notes:
#   1. This depends on the network specified in unbound.yml.
#   2. The orbital-sync container is configured for syncing with other Pi-hole instances
#      over Tailscale. Feel free to remove the service if this does not apply to you.

version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "10000:80/tcp"
    environment:
      TZ: 'Asia/Manila'
      WEBPASSWORD: '*************'
      PIHOLE_DNS_: '192.168.2.2#53'
      # DNSSEC: 'true'         # Uncomment if you disabled DNSSEC in Unbound
    volumes:
      - /etc/docker/compose/pihole/pihole:/etc/pihole
      - /etc/docker/compose/pihole/dnsmasq.d:/etc/dnsmasq.d
      # - /sys/class/thermal/thermal_zone1/temp:/sys/class/thermal/thermal_zone0/temp:ro
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.2.5

  orbital-sync:
    container_name: orbital-sync
    image: mattwebbio/orbital-sync:1
    depends_on:
      pihole:
        condition: service_healthy
    environment:
      PRIMARY_HOST_BASE_URL: 'http://192.168.1.3'
      PRIMARY_HOST_PASSWORD: '***************'
      SECONDARY_HOST_1_BASE_URL: 'http://rpi.bleak-bangus.ts.net'      # Tailscale
      SECONDARY_HOST_1_PASSWORD: '***************'
      INTERVAL_MINUTES: 1440
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro                           # Tailscale
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.2.6

networks:
  default:
    name: unbound
    external: true
