# Docker Compose spec for running Transmission through a VPN container
# by @jareddantis, 2023-2024
#
# Base path: /etc/docker/compose/transmission
# Required paths:
#   - config/, watch/, downloads/
#     > just create empty directory
#
# Notes:
#   1. The filebrowser service opens a simple web UI for uploading
#      torrent files to the watch folder. It's not necessary, but
#      it's convenient. Access via port 9092.

version: '3.8'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Manila
      - TRANSMISSION_WEB_HOME=/ui/flood
      - USER=transmission
      - PASS=<changeme>
    network_mode: 'container:gluetun'         # Comment this out if you're not using Wireguard
    # ports:                                  # UNcomment this out if you're not using Wireguard
    #   - 9091:9091/tcp                       # UNcomment this out if you're not using Wireguard
    #   - 51413:51413                         # UNcomment this out if you're not using Wireguard
    volumes:
      - /etc/docker/compose/transmission/config:/config
      - /etc/docker/compose/transmission/watch:/watch
      - /etc/docker/compose/transmission/flood-for-transmission:/ui/flood
      - /etc/docker/compose/transmission/downloads:/downloads
    restart: unless-stopped
